<br>

## Capstone Project

As the final requirement from the Masters of Information and Data Science (MIDS) program through UC Berkeley, the [Capstone course](https://datascience.berkeley.edu/academics/curriculum/synthetic-capstone-course) puts teams of 3-4 people together on a single, semester long, full data science life cycle project. The project allows us to put to use all of the skills accumulated throughout the program, as well as create a quality piece for our data science portfolio. 

<br>

## Team Members

#### Ray Buhr

- [LinkedIn Profile](https://www.linkedin.com/in/raybuhr)
- [Github Account](https://github.com/raybuhr)

#### Carson Forter

- [LinkedIn Profile](https://www.linkedin.com/in/carson-forter-3b13571b)
- [Github Account](https://github.com/cforter)

#### Satish Terala

- [LinkedIn Profile](https://www.linkedin.com/in/satishkt)
- [Github Account](https://github.com/satishkt)

<br>


## How It's Made

### Tech Stack

[SoftLayer](http://www.softlayer.com/) was used for the virtual servers hosting the website and database. Postgresql is the database we store data collected from the various data sources mentioned. The data collection came mostly from scripts written in R or Python. The content and styling for the website was generated using [Rmarkdown](http://rmarkdown.rstudio.com/rmarkdown_websites.html). The visualizations were made using the [fantastic libraries available in R](http://gallery.htmlwidgets.org/). The interactive prediction apps run on [Shiny Server](https://www.rstudio.com/products/shiny/shiny-server/). To quickly develop code in R using the same development environment, we use [RStudio Server](https://www.rstudio.com/products/rstudio/). To collaborate and share code, we use [Github](https://github.com/raybuhr/w210_beer_demand). For domain registration service we used [namecheap](https://www.namecheap.com/domains/registration.aspx).

### Predictions

The predictive model utilizes the Random Forest (RF) algorithm for regression. The RF algorithm reduces problems of overfitting by taking random population samples with replacement from the training dataset, as well as taking random samples of the features available. When using RF for regression, the predicted value at each node in a decision tree is the average response variable for all observations in the node, and predicted values are obtained by taking an average of individual tree. A standard measure of accuracy for regression models is the expected mean squared error, which for our model came out to 0.5.

*More details coming soon!*

<br>

## Lessons Learned  

- Finding and cleaning the various data sources actually did make up 80% of the project time
- There is not a lot of detailed, **open** information on the production and sales of individual breweries (the lowest level granularity we could find was at the state level)
- Social Media data (e.g. Twitter and Untappd) can be very messy (spelling, misusing words, sarcasm, etc.)
- There are some really weird names for beers (how tasty does *Dirty Old Man* sound?)
- There are some names for beers that don't make sentiment analysis easy (looking at you, *Bells Best Brown Ale*)
- A lot of the tweets about beer in Twitter actually forwarded from Untappd, so check for overlap in data sources!
- High quality data is more valuable for training a predictive model than large quantity of data points (~16,000 Untappd checkins vs. 1.5M BeerAdvocate reviews)
- Having regular check-ins and split responsibilities made project management and pivoting direction a lot easier
- The potential for this project far exceeds what we could deliver in only 3 months!

<br>

## Future Roadmap  

*What would have liked to do given more time or what we think should be the next steps for anyone wanting to contribute*

- Pull in social media data coming from breweries
- Add text sentiment aggregated by style to supplement maps
- Adapt style model to account for regional biases in data 
- Keep looking for new data sources to incorporate, ideally economic time series
- Get more feedback from breweries of what problems they have that data science can solve

<br>

## UC Berkeley MIDS Program

> The UC Berkeley School of Information (I School) offers the only professional [Master of Information and Data Science (MIDS)](https://datascience.berkeley.edu) delivered entirely online. The program is designed for professionals who want to solve real-world problems using complex and unstructured data, emphasizing the importance of asking meaningful research questions and effectively communicating findings. Delivered in a web-based learning environment, datascience@berkeley blends live, face-to-face classes with online coursework. The online learning experience facilitates collaboration, meaningful discussion, and lifelong connections with faculty and peers. datascience@berkeley is fully accredited by the Western Association of Schools & Colleges (WASC). 
