<br><br><br>

# Predicting the Demand of Beer Styles
*Capstone project for UC Berkeley MIDS, Sping 2016*

**Ray Buhr, Carson Forter, Satish Terala**

## GOAL:
### Help brewers make the right beer in the right place at the right time

## But Why Beer Models?

- Big industry
- Major year-over-year growth
- Few players in the data/beer space
- New players need data to succeed and represent an opportunity


## Data Science Approach

**Get data:**

- Sales data and consumption data from various sources
- Untappd, OpenBeerDB, FRED, Twitter

**Clean and transform data:**

- Load all data into uniform RDBMS

**Explore:**

- Do exploratory analysis to understand correlations and trends

**Model:**

- Build and test various models to predict ratings, sentiment, and consumption location, including multiple models by style and location

**Present and polish:**

- Visualize models in a Shiny dashboard for breweries to use

## Next Steps

- Build out website with interactive dashboard based on demo
- Add sentiment aggregated by style to supplement maps
- Adapt style model to account for regional biases in data 
- Keep looking for new data sources to incorporate
- Get more feedback from breweries of what problems they have that data science can solve